# Traitement de donn√©es

In [2]:
import os
os.chdir("./")
import pandas as pd
data = pd.read_csv("credit_customers.csv")
#data = pd.DataFrame(df)
data.head(100)

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6.0,critical/other existing credit,radio/tv,1169.0,no known savings,>=7,4.0,male single,none,...,real estate,67.0,none,own,2.0,skilled,1.0,yes,yes,good
1,0<=X<200,48.0,existing paid,radio/tv,5951.0,<100,1<=X<4,2.0,female div/dep/mar,none,...,real estate,22.0,none,own,1.0,skilled,1.0,none,yes,bad
2,no checking,12.0,critical/other existing credit,education,2096.0,<100,4<=X<7,2.0,male single,none,...,real estate,49.0,none,own,1.0,unskilled resident,2.0,none,yes,good
3,<0,42.0,existing paid,furniture/equipment,7882.0,<100,4<=X<7,2.0,male single,guarantor,...,life insurance,45.0,none,for free,1.0,skilled,2.0,none,yes,good
4,<0,24.0,delayed previously,new car,4870.0,<100,1<=X<4,3.0,male single,none,...,no known property,53.0,none,for free,2.0,skilled,2.0,none,yes,bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0<=X<200,54.0,no credits/all paid,business,15945.0,<100,<1,3.0,male single,none,...,no known property,58.0,none,rent,1.0,skilled,1.0,yes,yes,bad
96,no checking,12.0,critical/other existing credit,education,2012.0,no known savings,4<=X<7,4.0,female div/dep/mar,none,...,car,61.0,none,own,1.0,skilled,1.0,none,yes,good
97,0<=X<200,18.0,existing paid,business,2622.0,100<=X<500,1<=X<4,4.0,male single,none,...,car,34.0,none,own,1.0,skilled,1.0,none,yes,good
98,0<=X<200,36.0,critical/other existing credit,radio/tv,2337.0,<100,>=7,4.0,male single,none,...,real estate,36.0,none,own,1.0,skilled,1.0,none,yes,good
99,0<=X<200,20.0,delayed previously,used car,7057.0,no known savings,4<=X<7,3.0,male single,none,...,life insurance,36.0,bank,rent,2.0,high qualif/self emp/mgmt,2.0,yes,yes,good

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   checking_status         1000 non-null   object
 1   duration                1000 non-null   float64
 2   credit_history          1000 non-null   object
 3   purpose                 1000 non-null   object
 4   credit_amount           1000 non-null   float64
 5   savings_status          1000 non-null   object
 6   employment              1000 non-null   object
 7   installment_commitment  1000 non-null   float64
 8   personal_status         1000 non-null   object
 9   other_parties           1000 non-null   object
 10  residence_since         1000 non-null   float64
 11  property_magnitude      1000 non-null   object
 12  age                     1000 non-null   float64
 13  other_payment_plans     1000 non-null   object
 14  housing                 1000 non-null   object
 15  existing_credits        1000 non-null   float64
 16  job                     1000 non-null   object
 17  num_dependents          1000 non-null   float64
 18  own_telephone           1000 non-null   object
 19  foreign_worker          1000 non-null   object
 20  class                   1000 non-null   object
dtypes: float64(7), object(14)
memory usage: 164.2+ KB

In [4]:
data.isnull().sum()

checking_status           0
duration                  0
credit_history            0
purpose                   0
credit_amount             0
savings_status            0
employment                0
installment_commitment    0
personal_status           0
other_parties             0
residence_since           0
property_magnitude        0
age                       0
other_payment_plans       0
housing                   0
existing_credits          0
job                       0
num_dependents            0
own_telephone             0
foreign_worker            0
class                     0
dtype: int64

In [5]:
data.describe()

,duration,credit_amount,installment_commitment,residence_since,age,existing_credits,num_dependents
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,20.903000,3271.258000,2.973000,2.845000,35.546000,1.407000,1.155000
std,12.058814,2822.736876,1.118715,1.103718,11.375469,0.577654,0.362086
min,4.000000,250.000000,1.000000,1.000000,19.000000,1.000000,1.000000
25%,12.000000,1365.500000,2.000000,2.000000,27.000000,1.000000,1.000000
50%,18.000000,2319.500000,3.000000,3.000000,33.000000,1.000000,1.000000
75%,24.000000,3972.250000,4.000000,4.000000,42.000000,2.000000,1.000000
max,72.000000,18424.000000,4.000000,4.000000,75.000000,4.000000,2.000000

In [6]:
# Supprime toutes les lignes en doublon
data.drop_duplicates()

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6.0,critical/other existing credit,radio/tv,1169.0,no known savings,>=7,4.0,male single,none,...,real estate,67.0,none,own,2.0,skilled,1.0,yes,yes,good
1,0<=X<200,48.0,existing paid,radio/tv,5951.0,<100,1<=X<4,2.0,female div/dep/mar,none,...,real estate,22.0,none,own,1.0,skilled,1.0,none,yes,bad
2,no checking,12.0,critical/other existing credit,education,2096.0,<100,4<=X<7,2.0,male single,none,...,real estate,49.0,none,own,1.0,unskilled resident,2.0,none,yes,good
3,<0,42.0,existing paid,furniture/equipment,7882.0,<100,4<=X<7,2.0,male single,guarantor,...,life insurance,45.0,none,for free,1.0,skilled,2.0,none,yes,good
4,<0,24.0,delayed previously,new car,4870.0,<100,1<=X<4,3.0,male single,none,...,no known property,53.0,none,for free,2.0,skilled,2.0,none,yes,bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,no checking,12.0,existing paid,furniture/equipment,1736.0,<100,4<=X<7,3.0,female div/dep/mar,none,...,real estate,31.0,none,own,1.0,unskilled resident,1.0,none,yes,good
996,<0,30.0,existing paid,used car,3857.0,<100,1<=X<4,4.0,male div/sep,none,...,life insurance,40.0,none,own,1.0,high qualif/self emp/mgmt,1.0,yes,yes,good
997,no checking,12.0,existing paid,radio/tv,804.0,<100,>=7,4.0,male single,none,...,car,38.0,none,own,1.0,skilled,1.0,none,yes,good
998,<0,45.0,existing paid,radio/tv,1845.0,<100,1<=X<4,4.0,male single,none,...,no known property,23.0,none,for free,1.0,skilled,1.0,yes,yes,bad
999,0<=X<200,45.0,critical/other existing credit,used car,4576.0,100<=X<500,unemployed,3.0,male single,none,...,car,27.0,none,own,1.0,skilled,1.0,none,yes,good

In [7]:
hot = pd.get_dummies(data[['credit_history', 'checking_status', 'purpose', 'savings_status', 
                        'employment', 'personal_status', 'other_parties', 
                        'installment_commitment', 'residence_since', 'property_magnitude', 
                        'other_payment_plans', 'housing', 'existing_credits', 
                        'job', 'num_dependents', 'own_telephone', 'foreign_worker']])
hot
 #La fonction pd.get_dummies() est une fonction de Pandas qui permet de transformer des variables cat√©gorielles en variables binaires (ou indicatrices) 
 # en utilisant la m√©thode OneHot encoding.

,installment_commitment,residence_since,existing_credits,num_dependents,credit_history_all paid,credit_history_critical/other existing credit,credit_history_delayed previously,credit_history_existing paid,credit_history_no credits/all paid,checking_status_0<=X<200,...,housing_own,housing_rent,job_high qualif/self emp/mgmt,job_skilled,job_unemp/unskilled non res,job_unskilled resident,own_telephone_none,own_telephone_yes,foreign_worker_no,foreign_worker_yes
0,4.0,4.0,2.0,1.0,False,True,False,False,False,False,...,True,False,False,True,False,False,False,True,False,True
1,2.0,2.0,1.0,1.0,False,False,False,True,False,True,...,True,False,False,True,False,False,True,False,False,True
2,2.0,3.0,1.0,2.0,False,True,False,False,False,False,...,True,False,False,False,False,True,True,False,False,True
3,2.0,4.0,1.0,2.0,False,False,False,True,False,False,...,False,False,False,True,False,False,True,False,False,True
4,3.0,4.0,2.0,2.0,False,False,True,False,False,False,...,False,False,False,True,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,3.0,4.0,1.0,1.0,False,False,False,True,False,False,...,True,False,False,False,False,True,True,False,False,True
996,4.0,4.0,1.0,1.0,False,False,False,True,False,False,...,True,False,True,False,False,False,False,True,False,True
997,4.0,4.0,1.0,1.0,False,False,False,True,False,False,...,True,False,False,True,False,False,True,False,False,True
998,4.0,4.0,1.0,1.0,False,False,False,True,False,False,...,False,False,False,True,False,False,False,True,False,True
999,3.0,4.0,1.0,1.0,False,True,False,False,False,True,...,True,False,False,True,False,False,True,False,False,True

In [8]:
data = pd.concat([data, hot], axis = 1)
data = data.drop(['credit_history', 'checking_status', 'purpose', 'savings_status', 
                        'employment', 'personal_status', 'other_parties', 
                        'installment_commitment', 'residence_since', 'property_magnitude', 
                        'other_payment_plans', 'housing', 'existing_credits', 
                        'job', 'num_dependents', 'own_telephone', 'foreign_worker'], axis = 1)
data

,duration,credit_amount,age,class,credit_history_all paid,credit_history_critical/other existing credit,credit_history_delayed previously,credit_history_existing paid,credit_history_no credits/all paid,checking_status_0<=X<200,...,housing_own,housing_rent,job_high qualif/self emp/mgmt,job_skilled,job_unemp/unskilled non res,job_unskilled resident,own_telephone_none,own_telephone_yes,foreign_worker_no,foreign_worker_yes
0,6.0,1169.0,67.0,good,False,True,False,False,False,False,...,True,False,False,True,False,False,False,True,False,True
1,48.0,5951.0,22.0,bad,False,False,False,True,False,True,...,True,False,False,True,False,False,True,False,False,True
2,12.0,2096.0,49.0,good,False,True,False,False,False,False,...,True,False,False,False,False,True,True,False,False,True
3,42.0,7882.0,45.0,good,False,False,False,True,False,False,...,False,False,False,True,False,False,True,False,False,True
4,24.0,4870.0,53.0,bad,False,False,True,False,False,False,...,False,False,False,True,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,12.0,1736.0,31.0,good,False,False,False,True,False,False,...,True,False,False,False,False,True,True,False,False,True
996,30.0,3857.0,40.0,good,False,False,False,True,False,False,...,True,False,True,False,False,False,False,True,False,True
997,12.0,804.0,38.0,good,False,False,False,True,False,False,...,True,False,False,True,False,False,True,False,False,True
998,45.0,1845.0,23.0,bad,False,False,False,True,False,False,...,False,False,False,True,False,False,False,True,False,True
999,45.0,4576.0,27.0,good,False,True,False,False,False,True,...,True,False,False,True,False,False,True,False,False,True

In [9]:
# les colonne de la dataset apr√®s transformation
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 58 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   duration                                       1000 non-null   float64
 1   credit_amount                                  1000 non-null   float64
 2   age                                            1000 non-null   float64
 3   class                                          1000 non-null   object
 4   credit_history_all paid                        1000 non-null   bool
 5   credit_history_critical/other existing credit  1000 non-null   bool
 6   credit_history_delayed previously              1000 non-null   bool
 7   credit_history_existing paid                   1000 non-null   bool
 8   credit_history_no credits/all paid             1000 non-null   bool
 9   checking_status_0<=X<200                       1000 non-null   bool
 10  checking_status_<0                             1000 non-null   bool
 11  checking_status_>=200                          1000 non-null   bool
 12  checking_status_no checking                    1000 non-null   bool
 13  purpose_business                               1000 non-null   bool
 14  purpose_domestic appliance                     1000 non-null   bool
 15  purpose_education                              1000 non-null   bool
 16  purpose_furniture/equipment                    1000 non-null   bool
 17  purpose_new car                                1000 non-null   bool
 18  purpose_other                                  1000 non-null   bool
 19  purpose_radio/tv                               1000 non-null   bool
 20  purpose_repairs                                1000 non-null   bool
 21  purpose_retraining                             1000 non-null   bool
 22  purpose_used car                               1000 non-null   bool
 23  savings_status_100<=X<500                      1000 non-null   bool
 24  savings_status_500<=X<1000                     1000 non-null   bool
 25  savings_status_<100                            1000 non-null   bool
 26  savings_status_>=1000                          1000 non-null   bool
 27  savings_status_no known savings                1000 non-null   bool
 28  employment_1<=X<4                              1000 non-null   bool
 29  employment_4<=X<7                              1000 non-null   bool
 30  employment_<1                                  1000 non-null   bool
 31  employment_>=7                                 1000 non-null   bool
 32  employment_unemployed                          1000 non-null   bool
 33  personal_status_female div/dep/mar             1000 non-null   bool
 34  personal_status_male div/sep                   1000 non-null   bool
 35  personal_status_male mar/wid                   1000 non-null   bool
 36  personal_status_male single                    1000 non-null   bool
 37  other_parties_co applicant                     1000 non-null   bool
 38  other_parties_guarantor                        1000 non-null   bool
 39  other_parties_none                             1000 non-null   bool
 40  property_magnitude_car                         1000 non-null   bool
 41  property_magnitude_life insurance              1000 non-null   bool
 42  property_magnitude_no known property           1000 non-null   bool
 43  property_magnitude_real estate                 1000 non-null   bool
 44  other_payment_plans_bank                       1000 non-null   bool
 45  other_payment_plans_none                       1000 non-null   bool
 46  other_payment_plans_stores                     1000 non-null   bool
 47  housing_for free                               1000 non-null   bool
 48  housing_own                                    1000 non-null   bool
 49  housing_rent                                   1000 non-null   bool
 50  job_high qualif/self emp/mgmt                  1000 non-null   bool
 51  job_skilled                                    1000 non-null   bool
 52  job_unemp/unskilled non res                    1000 non-null   bool
 53  job_unskilled resident                         1000 non-null   bool
 54  own_telephone_none                             1000 non-null   bool
 55  own_telephone_yes                              1000 non-null   bool
 56  foreign_worker_no                              1000 non-null   bool
 57  foreign_worker_yes                             1000 non-null   bool
dtypes: bool(54), float64(3), object(1)
memory usage: 84.1+ KB

In [10]:
from sklearn import preprocessing
label_encoder_class = preprocessing.LabelEncoder()
data['class'] = label_encoder_class.fit_transform(data['class'])

# La fonction LabelEncoder attribue un num√©ro unique √† chaque cat√©gorie de la variable cat√©gorielle, 
# ce qui permet √† l'algorithme de traitement de donn√©es de comprendre comment les diff√©rentes cat√©gories 
# sont li√©es les unes aux autres.

S√©paration des variables caract√©ristiques et de la variable cible

In [11]:
X = data.drop('class', axis = 1)
X = X.values
y = data['class']

StandardScaler

In [12]:
# Nous utiliserons StandardScaler pour mettre nos donn√©es √† la m√™me √©chelle
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_standard = scaler.fit_transform(X)

# Construction de mod√®le

Transformer les donn√©es en train et test (30% test)

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(X_standard, y, test_size = 0.3, random_state = 0)

√âquilibrage des classes

In [14]:
# As we have many values ‚Äã‚Äãof a class and few values ‚Äã‚Äãof others, we will balance the classes 
# using OverSampling to make the classes balanced.
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler(random_state=0)
X_train, y_train = ros.fit_resample(X_train, y_train)

In [15]:
X_train.shape, y_train.shape

((972, 57), (972,))

In [16]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
clf = LinearDiscriminantAnalysis()
clf.fit(X_train, y_train)

LinearDiscriminantAnalysis()

Tester le mod√®le

In [17]:
# Mesure de performance
clf.score(X_test,y_test)

0.69

In [18]:
#matrice de confusion
pred = clf.predict(X_test)
from sklearn import metrics 
print(metrics.confusion_matrix(y_test,pred))

[[ 59  27]
 [ 66 148]]